"""Train TrackScorerNet from imitation-learning datasets.

Expected inputs are .pt files generated by:

    src/core/learning/generate_imitation_data.py

Example:

    python src/core/learning/train_track_scorer_imitation.py ^
        --train data/imitation/train.pt ^
        --val data/imitation/val.pt ^
        --model-output models/track_scorer_imitation.pt ^
        --epochs 80 ^
        --batch-size 256 ^
        --hidden-dim 128

The saved checkpoint is compatible with TrackScorerPlanner.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

from core.learning.track_scorer_model import TrackScorerNet


def load_dataset(path: str | Path) -> dict[str, Any]:
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Dataset not found: {path}")

    data = torch.load(path, map_location="cpu")

    required = [
        "global_features",
        "track_features",
        "action_masks",
        "labels",
        "extractor",
        "max_tracks",
        "global_dim",
        "track_dim",
    ]

    missing = [key for key in required if key not in data]
    if missing:
        raise ValueError(f"Dataset {path} is missing keys: {missing}")

    return data


def make_loader(
    dataset: dict[str, Any],
    batch_size: int,
    shuffle: bool,
) -> DataLoader:
    ds = TensorDataset(
        dataset["global_features"].float(),
        dataset["track_features"].float(),
        dataset["action_masks"].bool(),
        dataset["labels"].long(),
    )

    return DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=False,
    )


def validate_dataset_compatibility(
    train_data: dict[str, Any],
    val_data: dict[str, Any] | None,
) -> None:
    if val_data is None:
        return

    keys = ["extractor", "max_tracks", "global_dim", "track_dim"]

    for key in keys:
        if train_data[key] != val_data[key]:
            raise ValueError(
                f"Train/val mismatch for {key}: "
                f"train={train_data[key]} val={val_data[key]}"
            )


@torch.no_grad()
def evaluate(
    model: TrackScorerNet,
    loader: DataLoader,
    device: torch.device,
) -> dict[str, float]:
    model.eval()

    loss_fn = nn.CrossEntropyLoss()

    total_loss = 0.0
    total = 0
    correct = 0
    valid_label_count = 0

    for global_features, track_features, action_masks, labels in loader:
        global_features = global_features.to(device)
        track_features = track_features.to(device)
        action_masks = action_masks.to(device)
        labels = labels.to(device)

        scores = model(global_features, track_features, action_masks)
        loss = loss_fn(scores, labels)

        predictions = scores.argmax(dim=1)

        total_loss += float(loss.item()) * labels.shape[0]
        correct += int((predictions == labels).sum().item())
        total += int(labels.shape[0])

        rows = torch.arange(labels.shape[0], device=device)
        valid_label_count += int(action_masks[rows, labels].sum().item())

    return {
        "loss": total_loss / max(1, total),
        "accuracy": correct / max(1, total),
        "valid_label_fraction": valid_label_count / max(1, total),
    }


def train(args: argparse.Namespace) -> None:
    train_data = load_dataset(args.train)
    val_data = load_dataset(args.val) if args.val is not None else None
    validate_dataset_compatibility(train_data, val_data)

    device = torch.device("cuda" if torch.cuda.is_available() and not args.cpu else "cpu")
    print(f"Using device: {device}")

    train_loader = make_loader(
        train_data,
        batch_size=args.batch_size,
        shuffle=True,
    )

    val_loader = (
        make_loader(
            val_data,
            batch_size=args.batch_size,
            shuffle=False,
        )
        if val_data is not None
        else None
    )

    model = TrackScorerNet(
        global_dim=int(train_data["global_dim"]),
        track_dim=int(train_data["track_dim"]),
        hidden_dim=args.hidden_dim,
    ).to(device)

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.lr,
        weight_decay=args.weight_decay,
    )

    loss_fn = nn.CrossEntropyLoss()

    best_val_acc = -1.0
    best_state = None

    for epoch in range(args.epochs):
        model.train()

        total_loss = 0.0
        total = 0
        correct = 0
        valid_label_count = 0

        for global_features, track_features, action_masks, labels in train_loader:
            global_features = global_features.to(device)
            track_features = track_features.to(device)
            action_masks = action_masks.to(device)
            labels = labels.to(device)

            scores = model(global_features, track_features, action_masks)
            loss = loss_fn(scores, labels)

            optimizer.zero_grad(set_to_none=True)
            loss.backward()

            if args.grad_clip_norm is not None and args.grad_clip_norm > 0.0:
                torch.nn.utils.clip_grad_norm_(
                    model.parameters(),
                    max_norm=args.grad_clip_norm,
                )

            optimizer.step()

            predictions = scores.argmax(dim=1)

            total_loss += float(loss.item()) * labels.shape[0]
            correct += int((predictions == labels).sum().item())
            total += int(labels.shape[0])

            rows = torch.arange(labels.shape[0], device=device)
            valid_label_count += int(action_masks[rows, labels].sum().item())

        train_metrics = {
            "loss": total_loss / max(1, total),
            "accuracy": correct / max(1, total),
            "valid_label_fraction": valid_label_count / max(1, total),
        }

        if val_loader is not None:
            val_metrics = evaluate(model, val_loader, device)
            val_acc = val_metrics["accuracy"]

            if val_acc > best_val_acc:
                best_val_acc = val_acc
                best_state = {
                    key: value.detach().cpu().clone()
                    for key, value in model.state_dict().items()
                }

            print(
                f"epoch={epoch:03d} "
                f"train_loss={train_metrics['loss']:.4f} "
                f"train_acc={train_metrics['accuracy']:.3f} "
                f"val_loss={val_metrics['loss']:.4f} "
                f"val_acc={val_metrics['accuracy']:.3f} "
                f"label_valid={val_metrics['valid_label_fraction']:.3f}"
            )
        else:
            print(
                f"epoch={epoch:03d} "
                f"train_loss={train_metrics['loss']:.4f} "
                f"train_acc={train_metrics['accuracy']:.3f} "
                f"label_valid={train_metrics['valid_label_fraction']:.3f}"
            )

    if best_state is not None and args.save_best_val:
        model.load_state_dict(best_state)

    model_output = Path(args.model_output)
    model_output.parent.mkdir(parents=True, exist_ok=True)

    checkpoint = {
        "model_state_dict": model.state_dict(),
        "hidden_dim": int(args.hidden_dim),
        "max_tracks": int(train_data["max_tracks"]),
        "global_dim": int(train_data["global_dim"]),
        "track_dim": int(train_data["track_dim"]),
        "extractor": str(train_data["extractor"]),
        "num_train_examples": int(train_data["num_examples"]),
        "num_val_examples": int(val_data["num_examples"]) if val_data is not None else 0,
        "train_dataset": str(args.train),
        "val_dataset": str(args.val) if args.val is not None else None,
        "epochs": int(args.epochs),
        "batch_size": int(args.batch_size),
        "lr": float(args.lr),
        "weight_decay": float(args.weight_decay),
        "best_val_acc": float(best_val_acc),
    }

    torch.save(checkpoint, model_output)
    print(f"Saved model checkpoint to: {model_output}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()

    parser.add_argument("--train", type=str, required=True)
    parser.add_argument("--val", type=str, default=None)
    parser.add_argument("--model-output", type=str, default="models/track_scorer_imitation.pt")

    parser.add_argument("--epochs", type=int, default=80)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--hidden-dim", type=int, default=128)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--grad-clip-norm", type=float, default=5.0)

    parser.add_argument("--save-best-val", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--cpu", action="store_true")

    return parser.parse_args()


def main() -> None:
    args = parse_args()
    train(args)


if __name__ == "__main__":
    main()